{{- if .Values.config.s3Fetcher.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.s3Fetcher.secretName }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.config.s3Fetcher.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.config.s3Fetcher.secretAccessKey | b64enc | quote }}
  AWS_REGION: {{ .Values.config.s3Fetcher.region | b64enc | quote }}
  AWS_S3_PATH: {{ .Values.config.s3Fetcher.s3Path | b64enc | quote }}
{{- end }}
