name: Helm Chart CI

on:
  pull_request:
    branches: ["main"]
    paths:
      - "charts/**"

permissions:
  contents: write
  packages: write

jobs:
  test:
    uses: Aidan-Wallace/gh-workflows/.github/workflows/helm2-ci.yml@init
