name: Helm Chart CI

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - "charts/**"

permissions:
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.18.2

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.base_ref }})
          if [[ -n "$changed" ]]; then echo "changed=true" >> "$GITHUB_OUTPUT"; fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.base_ref }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          # https://github.com/kubernetes-sigs/kind
          version: "v0.29.0"

      - name: Run chart-testing (install+upgrade)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --upgrade --target-branch ${{ github.base_ref }}
