name: Release

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "charts/**"
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: "v3.18.2"

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package and Push Chart to GHCR
        run: |
          helm package ./charts/homepage --destination ./packaged
          helm push ./packaged/homepage-*.tgz oci://ghcr.io/${{ github.repository_owner }}
