name: Release

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "charts/**"
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.13.2

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Charts to GHCR
        run: |
          for chart_dir in charts/*/; do
            chart_name=$(basename "$chart_dir")
            version=$(grep '^version:' "$chart_dir/Chart.yaml" | awk '{print $2}')

            # Save and push using Helm's OCI support
            helm chart save "$chart_dir" "ghcr.io/${{ github.repository_owner }}/$chart_name:$version"
            helm chart push "ghcr.io/${{ github.repository_owner }}/$chart_name:$version"
          done
